Update error-messages.md
I am from Microsoft Azure CXP Chat Team. Got a customer case recently for the respective error message that cx got while trying to delete a VM on Azure and we found that this error is not documented in any MS public Docs. While I found out few such issues reported in Microsoft Community Threads.
hence updating this document with the same.

Customer Error : Failed to update associated resources for virtual machine 'xxx'
Message : An error occurred while updating associated resources for virtual machine 'xxx'. To delete the virtual machine without updating associated resources first, try again without updating any associated resource deletion states. 
Error: 'Changing property 'creationData' is not allowed.'